// <auto-generated />
using System;
using GestionLaboresAcademicas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestionLaboresAcademicas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251208042400_AgregarCamposEliminacionUsuario")]
    partial class AgregarCamposEliminacionUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AsignaturaUsuario", b =>
                {
                    b.Property<int>("AsignaturasId")
                        .HasColumnType("integer");

                    b.Property<int>("DocentesId")
                        .HasColumnType("integer");

                    b.HasKey("AsignaturasId", "DocentesId");

                    b.HasIndex("DocentesId");

                    b.ToTable("UsuarioAsignatura", (string)null);
                });

            modelBuilder.Entity("GestionLaboresAcademicas.Models.Asignatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Asignaturas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = "Ciencias Exactas",
                            Nombre = "Matemática"
                        },
                        new
                        {
                            Id = 2,
                            Area = "Comunicación",
                            Nombre = "Lenguaje"
                        },
                        new
                        {
                            Id = 3,
                            Area = "Ciencias Exactas",
                            Nombre = "Física"
                        });
                });

            modelBuilder.Entity("GestionLaboresAcademicas.Models.CredencialAcceso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BloqueadaHasta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("EsTemporal")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaExpiracion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequiereCambioPrimerLogin")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("CredencialesAcceso");
                });

            modelBuilder.Entity("GestionLaboresAcademicas.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Gestion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Grado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Paralelo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("GestionLaboresAcademicas.Models.DatosAcademicos.DatoAcademico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AsignaturaId")
                        .HasColumnType("integer");

                    b.Property<int>("CursoId")
                        .HasColumnType("integer");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("integer");

                    b.Property<int>("PeriodoAcademicoId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoDato")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("Id");

                    b.HasIndex("AsignaturaId");

                    b.HasIndex("CursoId");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("PeriodoAcademicoId");

                    b.ToTable("DatosAcademicos");

                    b.HasDiscriminator<string>("TipoDato").HasValue("DatoAcademico");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GestionLaboresAcademicas.Models.Estadisticas.BitacoraConsulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Exito")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FiltrosJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("MensajeError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TiposIndicador")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("BitacorasConsulta");
                });

            modelBuilder.Entity("GestionLaboresAcademicas.Models.PeriodoAcademico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Gestion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NombrePeriodo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("PeriodosAcademicos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "Activo",
                            FechaFin = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaInicio = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gestion = "Gestión 2025",
                            NombrePeriodo = "Gestión anual 2025"
                        });
                });

            modelBuilder.Entity("GestionLaboresAcademicas.Models.PoliticaSeguridad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IntentosMaximosFallidos")
                        .HasColumnType("integer");

                    b.Property<int>("LongitudMinimaPassword")
                        .HasColumnType("integer");

                    b.Property<int>("MinutosBloqueo")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiereCaracterEspecial")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiereMayusculas")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiereMinusculas")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiereNumero")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("PoliticasSeguridad");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IntentosMaximosFallidos = 5,
                            LongitudMinimaPassword = 8,
                            MinutosBloqueo = 15,
                            RequiereCaracterEspecial = true,
                            RequiereMayusculas = true,
                            RequiereMinusculas = true,
                            RequiereNumero = true
                        });
                });

            modelBuilder.Entity("GestionLaboresAcademicas.Models.RegistroAuditoriaUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ActorId")
                        .HasColumnType("integer");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("UsuarioAfectadoId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId1")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("UsuarioAfectadoId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioId1");

                    b.ToTable("RegistrosAuditoriaUsuarios");
                });

            modelBuilder.Entity("GestionLaboresAcademicas.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlcanceMaximo")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("RequiereAprobacion")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlcanceMaximo = "Institucion",
                            Descripcion = "Director de la institución",
                            Nombre = "Director",
                            RequiereAprobacion = true
                        },
                        new
                        {
                            Id = 2,
                            AlcanceMaximo = "Institucion",
                            Descripcion = "Secretaría académica",
                            Nombre = "Secretaria",
                            RequiereAprobacion = false
                        },
                        new
                        {
                            Id = 3,
                            AlcanceMaximo = "SusCursos",
                            Descripcion = "Docente",
                            Nombre = "Docente",
                            RequiereAprobacion = false
                        },
                        new
                        {
                            Id = 4,
                            AlcanceMaximo = "SuCurso",
                            Descripcion = "Estudiante",
                            Nombre = "Estudiante",
                            RequiereAprobacion = false
                        },
                        new
                        {
                            Id = 5,
                            AlcanceMaximo = "CursoHijos",
                            Descripcion = "Padre de familia",
                            Nombre = "Padre",
                            RequiereAprobacion = false
                        },
                        new
                        {
                            Id = 6,
                            AlcanceMaximo = "Institucion",
                            Descripcion = "Regente de disciplina",
                            Nombre = "Regente",
                            RequiereAprobacion = true
                        },
                        new
                        {
                            Id = 7,
                            AlcanceMaximo = "Biblioteca",
                            Descripcion = "Bibliotecario",
                            Nombre = "Bibliotecario",
                            RequiereAprobacion = true
                        });
                });

            modelBuilder.Entity("GestionLaboresAcademicas.Models.SolicitudAprobacionRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("FechaRespuesta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MotivoRechazo")
                        .HasColumnType("text");

                    b.Property<int>("RolSolicitadoId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioSolicitadoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RolSolicitadoId");

                    b.HasIndex("UsuarioSolicitadoId");

                    b.ToTable("SolicitudesAprobacionRoles");
                });

            modelBuilder.Entity("GestionLaboresAcademicas.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CursoId")
                        .HasColumnType("integer");

                    b.Property<string>("DocumentoCI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("EliminadoEl")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("EliminadoPor")
                        .HasColumnType("integer");

                    b.Property<string>("EstadoCuenta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ItemDocente")
                        .HasColumnType("text");

                    b.Property<string>("MotivoEliminacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("PendienteAsignacionCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("PendienteAsignarAsignaturas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("PendienteVinculoEstudiantes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("CursoId");

                    b.HasIndex("DocumentoCI")
                        .IsUnique();

                    b.HasIndex("EliminadoPor");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GestionLaboresAcademicas.Models.VinculoPadreEstudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsTutorLegal")
                        .HasColumnType("boolean");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("integer");

                    b.Property<int>("PadreId")
                        .HasColumnType("integer");

                    b.Property<string>("Relacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("PadreId");

                    b.ToTable("VinculosPadreEstudiante");
                });

            modelBuilder.Entity("GestionLaboresAcademicas.Models.DatosAcademicos.Asistencia", b =>
                {
                    b.HasBaseType("GestionLaboresAcademicas.Models.DatosAcademicos.DatoAcademico");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.ToTable("DatosAcademicos", t =>
                        {
                            t.Property("Fecha")
                                .HasColumnName("Asistencia_Fecha");
                        });

                    b.HasDiscriminator().HasValue("Asistencia");
                });

            modelBuilder.Entity("GestionLaboresAcademicas.Models.DatosAcademicos.Calificacion", b =>
                {
                    b.HasBaseType("GestionLaboresAcademicas.Models.DatosAcademicos.DatoAcademico");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Nota")
                        .HasColumnType("numeric");

                    b.Property<string>("TipoEvaluacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasDiscriminator().HasValue("Calificacion");
                });

            modelBuilder.Entity("GestionLaboresAcademicas.Models.DatosAcademicos.Matricula", b =>
                {
                    b.HasBaseType("GestionLaboresAcademicas.Models.DatosAcademicos.DatoAcademico");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("timestamp without time zone");

                    b.ToTable("DatosAcademicos", t =>
                        {
                            t.Property("Estado")
                                .HasColumnName("Matricula_Estado");
                        });

                    b.HasDiscriminator().HasValue("Matricula");
                });

            modelBuilder.Entity("GestionLaboresAcademicas.Models.DatosAcademicos.PrestamoBiblioteca", b =>
                {
                    b.HasBaseType("GestionLaboresAcademicas.Models.DatosAcademicos.DatoAcademico");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaPrestamo")
                        .HasColumnType("timestamp without time zone");

                    b.ToTable("DatosAcademicos", t =>
                        {
                            t.Property("Estado")
                                .HasColumnName("PrestamoBiblioteca_Estado");
                        });

                    b.HasDiscriminator().HasValue("PrestamoBiblioteca");
                });

            modelBuilder.Entity("AsignaturaUsuario", b =>
                {
                    b.HasOne("GestionLaboresAcademicas.Models.Asignatura", null)
                        .WithMany()
                        .HasForeignKey("AsignaturasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionLaboresAcademicas.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("DocentesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionLaboresAcademicas.Models.CredencialAcceso", b =>
                {
                    b.HasOne("GestionLaboresAcademicas.Models.Usuario", "Usuario")
                        .WithOne("CredencialAcceso")
                        .HasForeignKey("GestionLaboresAcademicas.Models.CredencialAcceso", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionLaboresAcademicas.Models.DatosAcademicos.DatoAcademico", b =>
                {
                    b.HasOne("GestionLaboresAcademicas.Models.Asignatura", "Asignatura")
                        .WithMany()
                        .HasForeignKey("AsignaturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionLaboresAcademicas.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionLaboresAcademicas.Models.Usuario", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionLaboresAcademicas.Models.PeriodoAcademico", "PeriodoAcademico")
                        .WithMany("DatosAcademicos")
                        .HasForeignKey("PeriodoAcademicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asignatura");

                    b.Navigation("Curso");

                    b.Navigation("Estudiante");

                    b.Navigation("PeriodoAcademico");
                });

            modelBuilder.Entity("GestionLaboresAcademicas.Models.Estadisticas.BitacoraConsulta", b =>
                {
                    b.HasOne("GestionLaboresAcademicas.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionLaboresAcademicas.Models.RegistroAuditoriaUsuario", b =>
                {
                    b.HasOne("GestionLaboresAcademicas.Models.Usuario", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GestionLaboresAcademicas.Models.Usuario", "UsuarioAfectado")
                        .WithMany()
                        .HasForeignKey("UsuarioAfectadoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GestionLaboresAcademicas.Models.Usuario", null)
                        .WithMany("AuditoriasComoActor")
                        .HasForeignKey("UsuarioId");

                    b.HasOne("GestionLaboresAcademicas.Models.Usuario", null)
                        .WithMany("AuditoriasComoAfectado")
                        .HasForeignKey("UsuarioId1");

                    b.Navigation("Actor");

                    b.Navigation("UsuarioAfectado");
                });

            modelBuilder.Entity("GestionLaboresAcademicas.Models.SolicitudAprobacionRol", b =>
                {
                    b.HasOne("GestionLaboresAcademicas.Models.Rol", "RolSolicitado")
                        .WithMany()
                        .HasForeignKey("RolSolicitadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionLaboresAcademicas.Models.Usuario", "UsuarioSolicitado")
                        .WithMany("SolicitudesRol")
                        .HasForeignKey("UsuarioSolicitadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RolSolicitado");

                    b.Navigation("UsuarioSolicitado");
                });

            modelBuilder.Entity("GestionLaboresAcademicas.Models.Usuario", b =>
                {
                    b.HasOne("GestionLaboresAcademicas.Models.Curso", "Curso")
                        .WithMany("Estudiantes")
                        .HasForeignKey("CursoId");

                    b.HasOne("GestionLaboresAcademicas.Models.Usuario", "UsuarioEliminador")
                        .WithMany()
                        .HasForeignKey("EliminadoPor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GestionLaboresAcademicas.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Rol");

                    b.Navigation("UsuarioEliminador");
                });

            modelBuilder.Entity("GestionLaboresAcademicas.Models.VinculoPadreEstudiante", b =>
                {
                    b.HasOne("GestionLaboresAcademicas.Models.Usuario", "Estudiante")
                        .WithMany("VinculosComoEstudiante")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionLaboresAcademicas.Models.Usuario", "Padre")
                        .WithMany("VinculosComoPadre")
                        .HasForeignKey("PadreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Padre");
                });

            modelBuilder.Entity("GestionLaboresAcademicas.Models.Curso", b =>
                {
                    b.Navigation("Estudiantes");
                });

            modelBuilder.Entity("GestionLaboresAcademicas.Models.PeriodoAcademico", b =>
                {
                    b.Navigation("DatosAcademicos");
                });

            modelBuilder.Entity("GestionLaboresAcademicas.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("GestionLaboresAcademicas.Models.Usuario", b =>
                {
                    b.Navigation("AuditoriasComoActor");

                    b.Navigation("AuditoriasComoAfectado");

                    b.Navigation("CredencialAcceso");

                    b.Navigation("SolicitudesRol");

                    b.Navigation("VinculosComoEstudiante");

                    b.Navigation("VinculosComoPadre");
                });
#pragma warning restore 612, 618
        }
    }
}
